export const CREATE_CURRENT_USER = 'CREATE_CURRENT_USER';

export const SAGA_GOOGLE_USER_START = "SAGA_GOOGLE_USER_START";
export const SAGA_EMAIL_USER_START = "SAGA_EMAIL_USER_START";

export const SAGA_USER_SUCCESS = "SAGA_USER_SUCCESS";
export const SAGA_USER_FAILED = "SAGA_USER_SUCCESS";

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
